### ISSUE TITLE
Sorry, just trying to get some advice

### ISSUE THREAD

**Issue by marlonsabala** [josephsellers/nextcloud-docker#1]
Hey Joseph, 

I'm sorry, I could not think of any other way of reaching out to you.
You seem to be using a similar plugin stack to me on wordpress (woo, woosubs, stripe gateway) and wanted to ask: 
Have you seen an increase in failed purchases recently?

We use a 1 week free trial on our subs. Basically, we only do a test with 0.00 charge on their card. But this fails quite a lot. Just trying to figure out if others have seen a similar trend. Or If it's best practice to charge, even if 1 euro. If the banks like that better.

Sorry. I just don't know about anyone else with experience whom I could reach out to.

Any advice would be amazing,
Marlon

**Comment by josephsellers** [comment]
Hi @marlonsabala,

> You seem to be using a similar plugin stack to me on wordpress (woo, woosubs, stripe gateway) and wanted to ask:
Have you seen an increase in failed purchases recently?

You're right, that's what we use. No, we haven't seen any noticeable increase in failed payments. 

>We use a 1 week free trial on our subs. Basically, we only do a test with 0.00 charge on their card. But this fails quite a lot. Just trying to figure out if others have seen a similar trend. Or If it's best practice to charge, even if 1 euro. If the banks like that better.

We do a trial with a very low rate (£1.20, while our main product is £12). We do this because we noticed when we offered a free trial lot of bounce once users were asked for card details. Whereas, when we offered a very cheap trial they are expecting to need to give the card details, and we have low bounce. 

I hope this helps :-)

**Comment by marlonsabala** [comment]
Hi @josephsellers 

Thank you very much for getting back to me.

Ah ok, so you implemented a cheap trial, not so much because of stripe/bank users on renewal, but because people just left the checkout page since they assumed they would not be asked for card details at all. Is that it?

Makes sense.
